package com.ut.emrPacs.model.dto.request.pacs.worklist;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.util.List;

@Data
public class WorklistReceivedStudyRequest {
    @Schema(description = "DicomServer callback event name.", example = "STUDY_RECEIVED")
    private String event;
    @Schema(description = "Optional source workflow status from the callback. Study metadata sync moves the row out of the active Worklist list.", example = "IN_PROGRESS")
    private String status;
    @Schema(description = "Worklist accession number used as the primary EMR match key.", example = "VIEW-SM-0005")
    private String accessionNumber;
    @Schema(description = "DicomServer study UUID.", example = "c958bd3d-5ba52826-744a96cb-686e0691-65ac3044")
    private String dicomServerStudyId;
    @Schema(description = "DicomServer patient UUID.", example = "1828c3f0-fb9402db-239b7259-9c86c4dd-acd62796")
    private String dicomServerPatientId;
    @Schema(description = "DicomServer series UUID list from the stable-study callback.", example = "[\"40d1ffe1-e43ebeda-5f7d0282-02589bd1-afeff9b4\"]")
    private List<String> dicomServerSeriesIds;
    @Schema(description = "Optional DICOM StudyInstanceUID when DicomServer callback provides it.", example = "1.2.826.0.1.3680043.8.498.92126578454577529120584583594987590614")
    private String studyInstanceUid;
    @Schema(description = "Image instance count observed by DicomServer before posting the callback. This is used only for callback validation and is not stored as image instance data.", example = "2")
    private Integer imageInstanceCount;
    @Schema(description = "Optional legacy callback field. When present it is used as a fallback study UUID.", example = "study-uuid-001")
    private String studyUuid;
    @Schema(description = "Patient ID echoed from DicomServer study tags.", example = "SEED-VIEW-SM-001")
    private String patientId;
    @Schema(description = "Patient name echoed from DicomServer study tags.", example = "Viewer Microscopy")
    private String patientName;
    @Schema(description = "Patient birth date from DicomServer in DICOM format.", example = "19790417")
    private String patientBirthDate;
    @Schema(description = "Patient sex from DicomServer.", example = "F")
    private String patientSex;
    @Schema(description = "Study description from DicomServer.", example = "Viewer Microscopy")
    private String studyDescription;
    @Schema(description = "Institution Name from DICOM study tags.", example = "TSNH HOSPITAL")
    private String institutionName;
    @Schema(description = "Study date from DicomServer in DICOM format.", example = "20260524")
    private String studyDate;
    @Schema(description = "Study time from DicomServer in DICOM format.", example = "130000")
    private String studyTime;
    @Schema(description = "Visit code generated by UDAYA_PACS_API Worklist flow.", example = "HSP001-20260511-000001")
    private String visitCode;
}
